services:
  - type: web
    name: online-sales-website-final # Changed name to ensure it's a fresh service
    env: node
    plan: free
    region: singapore # Or your preferred region

    buildCommand: "npm install && npm install --prefix frontend && npm run build --prefix frontend"
    startCommand: "node backend/server.js"
    
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: "mongodb+srv://onlineStoreUser:onlineStorePassword@cluster0.ixzoape.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        value: "a82013a6f2f298b8b7776803d627d1a0e689c14e2d481bbab9636e2a588e21a65207b1fd78b66f202e1ec81b338f8ba5844bd7c3e2c8471cd729f4abe3a254a9"
      - key: PAYPAL_CLIENT_ID
        value: "AXJ1XYFrhPbZJZPxKezKaeIM6I6KD1PEBS8ykKq5rYLnuO7Hsl143ymX0nUq-UaWGORXj7xQBP2G_DMs"